baseURL = "https://vijit-saxena.github.io/"
languageCode = "en-us"
title = "Vijit's Dev Blog"
theme = "PaperMod"

[params]
  author = "Vijit Saxena"

[taxonomies]
  tag = "tags"
  category = "categories"