baseURL = "https://vijit-saxena.github.io/"
languageCode = "en-us"
title = "Vijit Saxena"
theme = "PaperMod"
enableEmoji = true

[params]
  author = "Vijit Saxena"

[taxonomies]
  tag = "tags"
  category = "categories"